#!/bin/bash

# Stop at errors
set -ex

echo "### mybinder environment"
env
echo "### mybinder environment^^^"

# Manually install the necessary stuff for sisl
python3 -m pip install -vv tqdm matplotlib netCDF4 plotly .
