---
name: Wheel creation

# Change this to whatever you want
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release the wheels?'
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


permissions:
  contents: read

jobs:

  # Build the source distribution as well
  build_sdist:
    name: Build source dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build sdist
        run: |
          pipx run build --sdist

      - name: Check README rendering for PyPI
        run: |
          python -m pip install twine
          twine check dist/*

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          if-no-files-found: error

  # cibuildwheels already manages multiple python versions automatically
  # by just detecting the os. However, it does everything in the same job
  # and therefore in a serial manner. We build a matrix of operating systems
  # and python versions so that builds are ran in parallel.
  # The job matrix is basically copied from https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml
  wheels:
    name: "${{ matrix.os }} | ${{ matrix.cibw_archs }}"
    runs-on: ${{ matrix.os }}
    needs: build_sdist

    env:
      CIBW_SKIP: "*-musllinux_aarch64 pp*"

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # Linux
          #- os: ubuntu-latest
          #  cibw_archs: "x86_64"
          #- os: ubuntu-24.04-arm
          #  cibw_archs: "aarch64"

          ## MacOS
          #- os: macos-15-intel
          #  cibw_archs: "x86_64"
          #  deployment_target: "15.0"
          #- os: macos-14
          #  cibw_archs: "arm64"
          #  deployment_target: "14.0"

          # Windows
          - os: windows-latest
            cibw_archs: "AMD64"

    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Ensure fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 14

      - name: Build wheels for CPython 3.15
        if: matrix.os == 'not-now'
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "cp315t-* cp315-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_BUILD_FRONTEND:
            "pip; args: --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
          CIBW_BEFORE_TEST: >-
            pip install --pre
            --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
            numpy scipy
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target }}

      - name: Build wheels for CPython 3.14
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "cp314-* cp314t-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target }}

      - name: Build wheels for CPython 3.13
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "cp313-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target }}

      - name: Build wheels for CPython 3.12
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target }}

      - name: Build wheels for CPython 3.11
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target }}

      - name: Store artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ runner.os }}-${{ matrix.cibw_archs }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  wheels_pyodide:
    name: pyodide | wheels
    runs-on: ubuntu-latest
    needs: build_sdist

    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_BUILD: "cp311-* cp312-* cp313-* cp314-*"
          CIBW_PLATFORM: pyodide

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-pyodide
          path: wheelhouse/*.whl

  # Upload to testpypi
  upload_testpypi:
    needs: [build_sdist, wheels, wheels_pyodide]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: True

      - name: Print packages
        run: ls dist

      - uses: pypa/gh-action-pypi-publish@v1.14.2
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  # Check that the testpypi installation works
  test_testpypi:
    needs: [upload_testpypi]
    name: "${{ matrix.os }} | TestPyPi"
    runs-on: ${{ matrix.os }}

    strategy:
      # If one of the jobs fails, continue with the others.
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-latest, macos-14]

    steps:
      - name: Python installation
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Wait for testpypi to catch up
        run: |
          sleep 20
          version=${GITHUB_REF#refs/*/v}
          echo "SISL_VERSION=${version#refs/*/}" >> $GITHUB_ENV
          ls -lh

      - name: Install sisl + dependencies (oldest numpy, not ARM)
        if: matrix.os != 'macos-14'
        run: |
          python -m pip install -v \
            --progress-bar=off \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple/ \
            "sisl[test,viz]==${{ env.SISL_VERSION }}" \
            "numpy==1.24.*" "scipy==1.9.*" "xarray==2022.*"

      - name: Install sisl + dependencies (arm)
        if: matrix.os == 'macos-14'
        run: |
          python -m pip install -v \
            --progress-bar=off \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple/ \
            "sisl[test,viz]==${{ env.SISL_VERSION }}"

      - name: sisl debug info
        run: |
          python -c 'from sisl._debug_info import * ; print_debug_info()'

      - name: Test the installation
        run: |
          sdata --help

  # Upload to PyPI on every tag
  upload_pypi:
    needs: [test_testpypi]
    name: Publish to Pypi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: True

      - uses: pypa/gh-action-pypi-publish@v1.14.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
